@startuml

MasterMind *-- Board
MasterMind *-- CodeBreaker

Board o-- "0..10" Attempt
Board *-- SecretCode

CodeBreaker --> Attempt
CodeBreaker --> ValidationResult
CodeBreaker *-- Score
Score --> ValidationResult

Code <|-- Attempt
Code <|-- SecretCode
Code *-- "4" Position
Position o-- Color

Attempt *-- ValidationResult
Attempt --> AttemptValidator

SecretCode --> Randomizer
AttemptValidator --> ValidationResult
AttemptValidator --> SecretCode



Color <|-- ColorX : 6Colors

ValidationResult o-- "1x4" ValidationToken
ValidationToken <|-- RightColorAndPosition
ValidationToken <|-- WrongPosition
ValidationToken <|-- WrongColor

Randomizer --> Color

@enduml
